### ISSUE TITLE
Commits at bc repo that need to be add

### ISSUE THREAD

**Issue by rgaiacs** [aaren/swc-novice-python#2]
- [x] swcarpentry/bc@e28d108
- [x] swcarpentry/bc@4f5652b

**Comment by aaren** [comment]
@r-gaia-cs thanks. It is probably easier to keep committing to the bc repo rather than having people put PRs on this repo.

**Comment by rgaiacs** [comment]
> It is probably easier to keep committing to the bc repo rather than having people put PRs on this repo. 

As you wish.
